server:
  port: 8080

# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql #，每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    data: classpath:db/data.sql #，每次启动程序，程序都会运行data.sql文件，对数据库的数据操作
    url: jdbc:h2:mem:test;MODE=MYSQL;IGNORECASE=TRUE #配置h2数据库的连接地址
    username: sa
    password: sa
  h2:
    console:
      enabled: true #开启web console功能， http://127.0.0.1:8080/h2-console

#mybatis的相关配置
mybatis:
  #mapper配置文件
#  type-aliases-package: com.plumnix.app.mybatis.entity
  #开启驼峰命名
  configuration:
    og-impl: org.apache.ibatis.logging.stdout.StdOutImpl