# docker build -t producer-service:1.0 .
# docker run -d --name producer-service -p 9001:9001 producer-service:1.0
# docker run -d --name producer-service -v C:\Temporary\logs:/tmp/logs -p 9001:9001 producer-service:1.0
# java -javaagent:C:\Temporary\producer\skywalking-agent\agent\skywalking-agent.jar -Dskywalking.agent.service_name=ProducerServiceApplication -Dskywalking.collector.backend_service=152.136.46.93:11800 -jar producer-service.jar
FROM openjdk:11.0.3-jdk-stretch
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
VOLUME /tmp
RUN mkdir /tmp/logs
ADD producer-service.jar /tmp/app.jar
ADD skywalking-agent /tmp/skywalking-agent
ENTRYPOINT ["java","-javaagent:/tmp/skywalking-agent/agent/skywalking-agent.jar","-Dskywalking.agent.service_name=ProducerServiceApplication","-Dskywalking.collector.backend_service=152.136.46.93:11800","-jar","/tmp/app.jar"]
# ENTRYPOINT ["java","-jar","/app.jar","-c"]
EXPOSE 9001