# docker build -t consumer-service:1.0 .
# docker run -d --name consumer-service -p 9002:9002 consumer-service:1.0
# docker run -d --name consumer-service -v C:\Temporary\logs:/tmp/logs -p 9002:9002 consumer-service:1.0
# java -javaagent:C:\Temporary\consumer\skywalking-agent\agent\skywalking-agent.jar -Dskywalking.agent.service_name=consumerServiceApplication -Dskywalking.collector.backend_service=152.136.46.93:11800 -jar consumer-service.jar
FROM openjdk:11.0.3-jdk-stretch
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
VOLUME /tmp
RUN mkdir /tmp/logs
ADD consumer-service.jar /tmp/app.jar
ADD skywalking-agent /tmp/skywalking-agent
ENTRYPOINT ["java","-javaagent:/tmp/skywalking-agent/agent/skywalking-agent.jar","-Dskywalking.agent.service_name=consumerServiceApplication","-Dskywalking.collector.backend_service=152.136.46.93:11800","-jar","/tmp/app.jar"]
# ENTRYPOINT ["java","-jar","/app.jar","-c"]
EXPOSE 9002