server:
  port: 8080

#Spring Actuator
#management:
#  endpoint:
#    health:
#      show-details: always
#    info:
#      enabled: true
#    shutdown:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: shutdown,health,info,metrics,prometheus



#Prometheus
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

